### PR TITLE
Add debug console and debugging keys

### PR DESCRIPTION
**Pull request by tilderain**
One of my favorite features from NXEngine. Implementation might be a bit sloppy, but I hope someone better than me can fix it

### CODE REVIEW

**Comment by GabrielRavier** [comment]
If you're not actually finished with the PR, you might want to make this a Draft Pull Request

**Comment by Clownacy** [comment]
I want to hold-off on merging this until after the next release.

**Comment by GabrielRavier** [comment]
It has merge conflicts too

**Comment by Clownacy** [comment]
The enhanced branches have been discontinued.

**Pull request closed without merging**
