### PR TITLE
portable: Fix TSC_BUFFER_SIZE crash

### PR DESCRIPTION
**Pull request by GabrielRavier**
If the game is fed a sufficiently big TSC file, the game SIGSEGVs. I know this doesn't happen in vanilla, but at least we could just fail to load the TSC if the TSC file is too big.

### CODE REVIEW

**Comment by Clownacy** [comment]
This isn't within the scope of this branch.

**Comment by GabrielRavier** [comment]
I mean, I guess being able to crash the game by doing `dd if=/dev/zero bs=1000000 count=1 >data/Head.tsc && ./CSE2` isn't exactly *that* much of a portability concern, just something that affects general stability. Idk why I considered improved stability to affect portability but I'll take PHILOSOPHY.md to the letter and close this, then :shrug:.

**Comment by Clownacy** [comment]
Now that I think about it, this could make it into the `accurate` branch as a `FIX_BUGS` thing.

**Comment by GabrielRavier** [comment]
I'll make a PR for that ASAP.

**Pull request closed without merging**
